"""One-off asset generator for gcs-brochure-builder.

Rasterizes the brand SVG logos to PNG (pptxgenjs cannot embed SVG when run
in Node — see SKILL.md "SVG logos" risk note) and pre-renders the back-cover
radial-gradient background as a flat PNG (pptxgenjs shapes have no gradient
fill). Re-run this only if the source SVGs/gradient spec change.

The 5 social/pin icons used by components/back-cover.js are generated by
scripts/icons.py (get_social_icon_png) — the same rasterize-and-cache
mechanism used for any Material Symbols content icon — and copied here to
their canonical assets/icons/{name}.png path so back-cover.js's paths don't
need to change. See scripts/icons.py for the source SVG markup.

Usage: python3 scripts/gen-assets.py
"""

import shutil
import cairosvg
from pathlib import Path
from PIL import Image
import numpy as np

from icons import get_social_icon_png, SOCIAL_ICONS

ROOT = Path(__file__).resolve().parent.parent
BROCHURE_LOGOS = ROOT.parent / "gcs-brochure" / "assets" / "logos"
OUT_LOGOS = ROOT / "assets" / "logos"
OUT_COVERS = ROOT / "assets" / "covers"
OUT_ICONS = ROOT / "assets" / "icons"

RASTER_SCALE = 6  # ~6x the SVG's native px size, plenty for A4 print at 96dpi base

# back-cover.js places these on the Night Blue background — pin is pure
# white, the 4 social marks use the muted lavender tint from the original
# skills/gcs-brochure/assets/covers/back-cover.html markup.
SOCIAL_ICON_FILLS = {"pin": "#FFFFFF", "linkedin": "#B3B5CD", "facebook": "#B3B5CD", "instagram": "#B3B5CD", "youtube": "#B3B5CD"}


def rasterize_icons():
    # 192px matches the old scale=8-on-a-24px-viewBox rasterization this
    # replaces — keep print-quality headroom at the icons' actual ~20px
    # on-slide size (see components/back-cover.js).
    OUT_ICONS.mkdir(parents=True, exist_ok=True)
    for name in SOCIAL_ICONS:
        src = get_social_icon_png(name, fill_hex=SOCIAL_ICON_FILLS.get(name, "#FFFFFF"), size_px=192)
        out_path = OUT_ICONS / f"{name}.png"
        shutil.copyfile(src, out_path)
        print(f"icon -> {out_path.relative_to(ROOT)}")

def rasterize_logos():
    OUT_LOGOS.mkdir(parents=True, exist_ok=True)
    for svg_path in sorted(BROCHURE_LOGOS.glob("*.svg")):
        out_path = OUT_LOGOS / (svg_path.stem + ".png")
        cairosvg.svg2png(
            url=str(svg_path),
            write_to=str(out_path),
            scale=RASTER_SCALE,
            background_color=None,
        )
        print(f"logo -> {out_path.relative_to(ROOT)}")


def gen_back_cover_gradient():
    """Approximates: radial-gradient(1146px 1196px at 101.45% 0%, #000957 0%, #0F1A2D 100%)
    over the 794x1123 (A4 @96dpi) brochure canvas, rendered at 3x for print quality."""
    W, H = 794 * 3, 1123 * 3
    cx, cy = 1.0145 * W, 0.0 * H  # gradient center: 101.45% x, 0% y (CSS % is of the box, not the radius box)
    rx, ry = 1146 * 3, 1196 * 3
    c0 = (0x00, 0x09, 0x57)  # #000957
    c1 = (0x0F, 0x1A, 0x2D)  # #0F1A2D

    yy, xx = np.mgrid[0:H, 0:W]
    d = np.sqrt(((xx - cx) / rx) ** 2 + ((yy - cy) / ry) ** 2)
    t = np.clip(d, 0.0, 1.0)[..., None]  # (H, W, 1)
    c0_arr = np.array(c0, dtype=np.float64)
    c1_arr = np.array(c1, dtype=np.float64)
    rgb = np.round(c0_arr + t * (c1_arr - c0_arr)).astype(np.uint8)

    out_path = OUT_COVERS / "background-back-cover.png"
    Image.fromarray(rgb).save(out_path)
    print(f"back-cover gradient -> {out_path.relative_to(ROOT)}")


if __name__ == "__main__":
    rasterize_logos()
    rasterize_icons()
    gen_back_cover_gradient()
